import { ArrowUpRight } from 'lucide-react';
import { Mascot } from '../../components/Mascot';
import type { Funcionario } from '../../types/funcionario';
import { initials, money, statusClass, statusLabel } from '../../utils/format';

interface Props { funcionarios: Funcionario[]; indicadores: { total?:number; emAnalise?:number; aprovados?:number; reprovados?:number; contratados?:number }; onOpenCandidates:()=>void; onView:(id:number)=>void; }
export function Dashboard({ funcionarios, indicadores, onOpenCandidates, onView }: Props) {
  const local = (s:string)=>funcionarios.filter(f=>f.status===s).length;
  const count = (s:string)=>s==='EM_ANALISE'?(indicadores.emAnalise ?? local(s)):s==='APROVADO'?(indicadores.aprovados ?? local(s)):s==='REPROVADO'?(indicadores.reprovados ?? local(s)):(indicadores.contratados ?? local(s));
  const total = indicadores.total ?? funcionarios.length;
  const deps=Object.entries(funcionarios.reduce<Record<string,number>>((a,f)=>{const d=f.departamento||'Não informado';a[d]=(a[d]||0)+1;return a;},{})).sort((a,b)=>b[1]-a[1]).slice(0,5);
  const maxDep=Math.max(1,...deps.map(([,n])=>n));
  const chart=[['Em análise',count('EM_ANALISE'),'bar-coral'],['Aprovados',count('APROVADO'),'bar-lime'],['Reprovados',count('REPROVADO'),'bar-muted'],['Contratados',count('CONTRATADO'),'bar-green']] as const;
  const maxChart=Math.max(1,...chart.map(([,n])=>n));
  const recent=[...funcionarios].sort((a,b)=>b.id-a.id).slice(0,5);
  return <div className="page-stack">
    <section className="hero-card"><div><div className="hero-kicker">Processo de contratação</div><h2>Olá! 👋</h2><p>{count('EM_ANALISE')} candidatos aguardam avaliação e {count('APROVADO')} já estão aprovados para contratação.</p><button className="btn btn-lime hero-action" onClick={onOpenCandidates}>Ver candidatos <ArrowUpRight size={15}/></button></div><div className="hero-art mascot-hero"><div className="mascot-frame"><Mascot size={104} /></div><span>Seu copiloto de RH</span></div></section>
    <section className="metric-grid"><Metric label="Total" value={total} hint="candidatos no processo"/><Metric label="Em análise" value={count('EM_ANALISE')} hint="aguardando avaliação"/><Metric label="Aprovados" value={count('APROVADO')} hint="aptos à contratação" accent/><Metric label="Contratados" value={count('CONTRATADO')} hint="admissão concluída" accent/></section>
    <section className="dashboard-grid"><div className="page-stack"><div className="card"><div className="section-header"><div><h3>Progresso do recrutamento</h3><span>Visão resumida dos últimos candidatos.</span></div><button className="link-button" onClick={onOpenCandidates}>Ver tudo</button></div><div className="table-wrap"><table><thead><tr><th>Nome</th><th>Cargo</th><th>Etapa</th><th>Salário</th></tr></thead><tbody>{funcionarios.slice(0,6).map(f=><tr className="clickable-row" key={f.id} onClick={()=>onView(f.id)}><td><div className="name-cell"><span className="avatar">{initials(f.nome)}</span><div><strong>{f.nome}</strong><small>{f.email}</small></div></div></td><td>{f.cargo}</td><td><span className={statusClass(f.status)}>{statusLabel(f.status)}</span></td><td>{money(f.salario)}</td></tr>)}</tbody></table>{!funcionarios.length&&<div className="empty-state">Nenhum funcionário foi carregado da API.</div>}</div></div></div><div className="page-stack"><div className="card"><div className="section-header"><div><h3>Candidatos recentes</h3><span>Registros mais novos.</span></div><button className="link-button" onClick={onOpenCandidates}>ver todos</button></div><div className="recent-list">{recent.map(f=><button className="recent-item" key={f.id} onClick={()=>onView(f.id)}><span className="avatar">{initials(f.nome)}</span><span className="recent-copy"><strong>{f.nome}</strong><small>{f.cargo}</small></span><span className={statusClass(f.status)}>{statusLabel(f.status)}</span></button>)}</div>{!recent.length&&<div className="empty-state">Sem registros.</div>}</div><div className="card"><div className="section-header"><div><h3>Distribuição por status</h3><span>Quantidade de candidatos.</span></div></div><div className="chart">{chart.map(([label,value,cls])=><div className="chart-col" key={label}><strong>{value}</strong><div className={`chart-bar ${cls}`} style={{height:`${Math.max(8,Math.round(value/maxChart*100))}px`}}/><small>{label}</small></div>)}</div></div><div className="card"><div className="section-header"><div><h3>Por departamento</h3><span>Concentração atual.</span></div></div><div className="dept-list">{deps.map(([label,value])=><div className="dept-item" key={label}><div><span>{label}</span><b>{value}</b></div><div className="progress"><span style={{width:`${value/maxDep*100}%`}}/></div></div>)}{!deps.length&&<div className="empty-state">Sem dados de departamentos.</div>}</div></div></div></section>
  </div>;
}
function Metric({label,value,hint,accent=false}:{label:string;value:number;hint:string;accent?:boolean}){return <div className="card metric-card"><div className="metric-label">{label}</div><div className={`metric-value ${accent?'accent-value':''}`}>{value}</div><div className="metric-hint">{hint}</div></div>}
